version: '3.8'

# ============================================
# EscolarOnline - Docker Compose (Producción AWS)
# Arquitectura de 3 Capas
# ============================================

services:
  # Frontend (Nginx + HTML/CSS/JS)
  frontend:
    build: ./microservicioFrontend
    container_name: escolaronline-frontend
    ports:
      - "80:80" # Modificado para recibir el tráfico del ALB
    depends_on:
      - get-products
      - create-product
      - update-product
      - delete-product
    networks:
      - escolaronline-net

  # Microservicio: Consultar productos (GET)
  get-products:
    build: ./microserviciosBackend/get-products
    container_name: escolaronline-get-products
    # Puertos eliminados por seguridad perimetral
    environment:
      DB_HOST: ${DB_HOST} # <-- DEBES ACTUALIZAR ESTO
      DB_USER: alumno
      DB_PASS: alumno123
      DB_NAME: escolar_online
      DB_PORT: 3306
      PORT: 3001
    networks:
      - escolaronline-net

  # Microservicio: Crear producto (POST)
  create-product:
    build: ./microserviciosBackend/create-product
    container_name: escolaronline-create-product
    environment:
      DB_HOST: ${DB_HOST} # <-- DEBES ACTUALIZAR ESTO
      DB_USER: alumno
      DB_PASS: alumno123
      DB_NAME: escolar_online
      DB_PORT: 3306
      PORT: 3002
    networks:
      - escolaronline-net

  # Microservicio: Modificar producto (PUT)
  update-product:
    build: ./microserviciosBackend/update-product
    container_name: escolaronline-update-product
    environment:
      DB_HOST: ${DB_HOST} # <-- DEBES ACTUALIZAR ESTO
      DB_USER: alumno
      DB_PASS: alumno123
      DB_NAME: escolar_online
      DB_PORT: 3306
      PORT: 3003
    networks:
      - escolaronline-net

  # Microservicio: Eliminar producto (DELETE)
  delete-product:
    build: ./microserviciosBackend/delete-product
    container_name: escolaronline-delete-product
    environment:
      DB_HOST: ${DB_HOST} # <-- DEBES ACTUALIZAR ESTO
      DB_USER: alumno
      DB_PASS: alumno123
      DB_NAME: escolar_online
      DB_PORT: 3306
      PORT: 3004
    networks:
      - escolaronline-net

networks:
  escolaronline-net:
    driver: bridge